### ISSUE TITLE
Bowtie 2によるリードのゲノムへのマッピングでエラーが出る

### ISSUE THREAD

**Issue by qqsearch** [yuifu/ngsdat2_epigenome_chipseq#1]
環境はLinux CentOSです。

(base) [chipseq]$ bowtie2 -p 2 -x data/external/bowtie2_index/mm10 \
    -U BRD4_ChIP_IFNy.R1.trim.fastq.gz > bowtie2/BRD4_ChIP_IFNy.trim.sam
(ERR): "data/external/bowtie2_index/mm10" does not exist or is not a Bowtie 2 index
Exiting now ...

Macでの操作でないため -p 2 は除外して、homeディレクトリの直下であるため data/external/を抜いて行いましたが、下記のエラーが出ます。

(base) [chipseq]$ bowtie2 -x ~/bowtie2_index/mm10 -U BRD4_ChIP_IFNy.R1.trim.fastq.gz > bowtie2/BRD4_ChIP_I
FNy.trim.sam
stat: Bad file descriptor
Warning: Could not open read file "BRD4_ChIP_IFNy.R1.trim.fastq.gz" for reading; skipping...
Error: No input read files were valid
(ERR): bowtie2-align exited with value 1

**Comment by yuifu** [comment]
エラーメッセージを一見すると、 `BRD4_ChIP_IFNy.R1.trim.fastq.gz` に何かおかしなことが起きているように見えます。

まず、 以下の２つのコマンドを実行し、それぞれの出力をお知らせいただけますでしょうか？


```
ls -lsh BRD4_ChIP_IFNy.R1.trim.fastq.gz
```


```
gzip -dc BRD4_ChIP_IFNy.R1.trim.fastq.gz | head
```

**Comment by qqsearch** [comment]
ご対応ありがとうございます。
```
bowtie2 -x ~/bowtie2_index/mm10 \ -U ~/chipseq/fastp/BRD4_ChIP_IFNy.R1.trim.fastq.gz > bowtie2/BRD4_ChIP_IFNy.trim.sam
```
fastpフォルダの参照を追記して解決しました。




```
$ ls -lsh BRD4_ChIP_IFNy.R1.trim.fastq.gz
877M -rw-r--r-- 1 [] rn-kumed 877M Sep 30 11:02 BRD4_ChIP_IFNy.R1.trim.fastq.gz
```


```
$ gzip -dc BRD4_ChIP_IFNy.R1.trim.fastq.gz | head
@SRR5208824.5 5/1
ACTGANACTTCTGTTTCCCCAAAAACACCCCCCAANNNNACAGCCTAGACAGGAAACCATTGAAAAGAACTCTTT
+
AAAAA#AEEEEEEEEAEEEEAAEEEEEEEEEEEAE####EEEEEE/E66EEEEA/EEEAEEEE6EEE/EE/AE<E
@SRR5208824.6 6/1
CCTGCNTTGCGCTCTGTCCCCCCTACCACGTGCCANNTNCCAACCCACGTATTTGCTCTGCGCCTCTGACTTCTA
+
6AAAA#AAEEE/EEEEEEEEEEEE/EEEEEEE/EE##E#EEE/EEEEEEEEEEEEEEE6AEEEEEE/AAEEEEEA
@SRR5208824.7 7/1
TCTCTNAACAGGGAATTCCTCCACAAATCCCCTAGNNCNTCTGTCAACAAGTGCCTTGGGTCCTTGATTGCAGGT
```

**Comment by yuifu** [comment]
こちらこそありがとうございます。

`fastp` フォルダの参照を追記して、修正しました：
2416cc6a57f446eaef6d35c9ddcf6039b6af9717
