### ISSUE TITLE
125ページのゲノムへのマッピングについて

### ISSUE THREAD

**Issue by nakane-scc** [yuifu/ngsdat2_epigenome_chipseq#7]
bowtie2 -p 2 -x /Volumes/DATA/bowtie2_index/mm10 -U fastp/BRD4_ChIP_IFNy.R1.trim.fastq.gz > bowtie2/BRD4_ChIP_IFNy.trim.sam
と入力したところ（システムドライブの容量の問題で、DATAドライブで作業しております）、
(ERR): Description of arguments failed!
Exiting now ...
というエラメッセージが出てしまいました。
どのように対処すればよろしいでしょうか。

お忙しいとは存じますが、回答いただければ幸いです。

**Comment by yuifu** [comment]
バージョンを確認していただけますでしょうか？

```
bowtie2 --version
```

**Comment by nakane-scc** [comment]
ご回答ありがとうございます。

私もバージョンの問題かと思い、
$ bowtie2 --version
とコマンドを打ったところ、
(ERR): Description of arguments failed!
Exiting now ...
と、同じエラーメッセージが出てしまいました。

$ bowtie2 --help
でも同じエラーが出るのですが、コマンドが見つからないというエラーではないので、インストールはされているのではないかと思っているのですが。

よろしくお願いいたします。

**Comment by yuifu** [comment]
おそらくインストールが適切に終了していないのだと思います。

bowtie2 を一度削除してインストールし直していただけますでしょうか？
その際に、エラーや警告のメッセージがあるかを確認していただければと思います。

**Comment by nakane-scc** [comment]
アンインストールしてからインストールし直した方がいいのではないかと思いましたが、アンインストールの仕方がわからないので、
$ conda install -c bioconda bowtie2
と、改めてインストールしたところ、
Collecting package metadata (repodata.json): done
Solving environment: done

# All requested packages already installed.
と表示され、改めてインストールされなかったようです。実際、
$ bowtie2 --version
とバージョン確認をしましたが、以下のように同じエラーメッセージが出てしまいました。
(ERR): Description of arguments failed!
Exiting now ...

アンインストールが必要でしたら、アンインストールの仕方も教えていただければと存じます。

**Comment by yuifu** [comment]
## アンインストール

```
conda uninstall bowtie2
```

https://qiita.com/naz_/items/84634fbd134fbcd25296

## 再インストールの前に

```
conda update conda
```

## 再インストール

```
conda install -c bioconda bowtie2
```

**Comment by nakane-scc** [comment]
何度もすいません。

$ conda uninstall bowtie2でアンインストールをしようとしたところ、
Collecting package metadata (repodata.json): done
Solving environment: |
というところで、「|」がぐるぐる回転したまま30分近く経過したため、パソコンを再起動して同様の作業をしたのですが、やはり、
Solving environment: |
のところで先に進みません。

Biocondaをアンインストールして入れ直さないとダメでしょうか。

**Comment by yuifu** [comment]
これはいかがでしょうか？

```
conda uninstall  --override-channels -c bioconda bowtie2
```

**Comment by nakane-scc** [comment]
ご回答、ありがとうございました。

教えていただいたコマンドで処理が進み、アンインストール完了後に、conda update condaを実行し、最後にconda install -c bioconda bowtie2にてbowtie2を再インストールいたしました。

確認のため、再びバージョンチェックを行ったところ、
dyld: Library not loaded: @rpath/libtbb.dylib
  Referenced from: /Users/cancer-c/anaconda3/bin/bowtie2-align-s
  Reason: image not found
(ERR): Description of arguments failed!
Exiting now ...
というエラーメッセージが出てしまいました。

私なりに調べ、/Users/cancer-c/anaconda3/bin/bowtie2-align-sにlibtbb.dylibがないということなのではないかと思い、
$ find / -name libtbb.dylib
を実行したところ、
/Users/cancer-c/anaconda3/pkgs/tbb-2019.8-h770b8ee_0/lib/libtbb.dylib
という結果が得られたため、シンボリックリンクを貼って対応しようと考え、
$ ln -s /Users/cancer-c/anaconda3/pkgs/tbb-2019.8-h770b8ee_0/lib/libtbb.dylib /Users/cancer-c/anaconda3/bin/bowtie2-align-s
を行い、改めてバージョンチェックをしました。しかし、下記の通り、全く同じエラーメッセージが出てしまいました。
dyld: Library not loaded: @rpath/libtbb.dylib
  Referenced from: /Users/cancer-c/anaconda3/bin/bowtie2-align-s
  Reason: image not found
(ERR): Description of arguments failed!
Exiting now ...

何度もお手を煩わせて恐縮ですが、対応策をご教授いただければ幸いです。

**Comment by nakane-scc** [comment]
46ページでBiocondaをインストールする前に、Anacondaをインストールしていたのですが、これらが干渉して不具合を起こしているということはないでしょうか。
片方、あるいは両方を一度アンインストールしようとしたのですが、きれいにアンインストールする方法がまだ見つかっていません。

**Comment by nakane-scc** [comment]
https://oversleptabit.com/archives/4570
https://weblabo.oscasierra.net/python-anaconda-uninstall-macos/
上記サイトを参考に、完全ではないかもしれませんが、miniconda、anacondaを１度アンインストールしました。

その後、Miniconda3-py39_4.9.2-MacOSX-x86_64をインストールし、bowtie2をインストールしようとしたのですが、下記のようなエラーメッセージが出てしまい、先に進むことができませんでした。

Collecting package metadata (current_repodata.json): failed
WARNING conda.exceptions:print_unexpected_error_report(1213): KeyError('pkgs_dirs')
Traceback (most recent call last):
  File "/Users/miniconda3/lib/python3.9/site-packages/conda/exceptions.py", line 1079, in __call__
    return func(*args, **kwargs)
（略）
ImportError: dlopen(/Users/miniconda3/lib/python3.9/lib-dynload/_ctypes.cpython-39-darwin.so, 2): Library not loaded: @rpath/libffi.6.dylib
  Referenced from: /Users/miniconda3/lib/python3.9/lib-dynload/_ctypes.cpython-39-darwin.so
  Reason: image not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/miniconda3/lib/python3.9/site-packages/conda/exceptions.py", line 1211, in print_unexpected_error_report
    message_builder.append(get_main_info_str(error_report['conda_info']))
  File "/Users/miniconda3/lib/python3.9/site-packages/conda/cli/main_info.py", line 240, in get_main_info_str
    info_dict['_' + key] = ('\n' + 26 * ' ').join(info_dict[key])
KeyError: 'pkgs_dirs'

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/Users/miniconda3/lib/python3.9/site-packages/conda/exceptions.py", line 1079, in __call__
        return func(*args, **kwargs)
（略）
    ImportError: dlopen(/Users/miniconda3/lib/python3.9/lib-dynload/_ctypes.cpython-39-darwin.so, 2): Library not loaded: @rpath/libffi.6.dylib
      Referenced from: /Users/miniconda3/lib/python3.9/lib-dynload/_ctypes.cpython-39-darwin.so
      Reason: image not found

`$ /Users/miniconda3/bin/conda install -c bioconda bowtie2`

  environment variables:
conda info could not be constructed.
KeyError('pkgs_dirs')

An unexpected error has occurred. Conda has prepared the above report.

If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers?

[y/N]: y
Upload successful.

Thank you for helping to improve conda.
Opt-in to always sending reports (and not see this message again)
by running

    $ conda config --set report_errors true

**Comment by nakane-scc** [comment]
brewコマンドを使ったらbowtie2をインストールすることができ、125ページのマッピングもできました。
色々お手数をおかけしてしまい、失礼しました。

**Comment by yuifu** [comment]
@nakane-scc 返信が途切れて申し訳ありません。解決したとのこと、何よりです。
